version: "3"
services:
  auth:
    build: 
      context: .
      args: 
        NODE_ENV: dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
      - MONGODB_URI=mongodb://swiftycareer_dev:swiftycareer@23.242.50.55:27017/?authSource=admin
      - JWT_SECRET=1304b28485f34eacb1bed092f62d84e6
      - JWT_REFRESH_EXP=600