apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sc-ingress
  labels:
    name: sc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /feed(/|$)(.*)
        backend:
          service:
            name: feed-service
            port: 
              number: 3001
      - pathType: Prefix
        path: /auth(/|$)(.*)
        backend:
          service:
            name: user-service
            port: 
              number: 3002