apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      imagePullSecrets:
        - name: registry-key
      containers:
      - name: user
        image: gellert5225/sc-user-profile:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: MONGODB_URI
          value: mongodb://swiftycareer_dev:swiftycareer@23.242.50.55:27017/?authSource=admin
        - name: JWT_SECRET
          value: 1304b28485f34eacb1bed092f62d84e6
        - name: JWT_REFRESH_EXP
          value: "600"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
